# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAc28ONMZ26WyEJ5LHP1wHwy-FPyLvTR
"""

# Print all number in a range given by user which is divisble by given number
lower_range = int(input("Enter the lowest number : "))
higher_range = int(input("Enter the higher number : "))
div = int(input("Enter the number for divisble : "))

for elements in range(lower_range, higher_range + 1):
  if (elements % div == 0):
    print (elements)