# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1090Ar05uQ9mYNGgt-vx18C-avuY_TSh_
"""

# Write a program to enter the days of week.
# using list extract days

days_week = [None]*7
i = 0
while(i <= 6):
  days_week[i] = input(f"enter the {i} day of week\n ")
  i = i+1

print("Days of week are : ", days_week)

# Extract first half week
half_first_week = days_week[0:4]
print("Week days [first half] : ", half_first_week)

# Extract later half week
later_half_week = days_week[4:7]
print("Week days [later half] : ", later_half_week)

# Extract weekend days
weekend_days = days_week[-2:]
print("Weekend days : ",weekend_days)
