# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1090Ar05uQ9mYNGgt-vx18C-avuY_TSh_
"""

# Create a list of sandwitch ingredients and get some ingredients from the list

num_ingredients = int(input("Enter the number of ingredients you want to add: "))
list_ingredients = [None] * num_ingredients
print (f"Enter {num_ingredients} ingredints...")
i = 0
while(i < num_ingredients):
  list_ingredients[i] = input(f"enter ingredients {i+1} : ")
  i = i+1

print("List of ingredients : " ,list_ingredients)

#slicing to get first 2 ingredients
first_two = list_ingredients[0:2]
print("First 2 ingredients : ", first_two)

#slicing to get last 2 ingredients
last_two = list_ingredients[-2:]
print("Last 2 ingredients : ", last_two)

#slicing to get even index ingredients
even_numbers = list_ingredients[0:num_ingredients:2]
print("Ingredients on even idexes : ", even_numbers)